Feature - hot reload banlist
R2Northstar/NorthstarLauncher pull request #164
Opened 2022-05-03 16:32 UTC by dilirity

This fixes #163 and hopefully https://github.com/R2Northstar/Northstar/issues/251.

Not sure how to go about listen servers, since I don't know the equivalent for [isDedicated()](https://github.com/R2Northstar/NorthstarLauncher/blob/6c8112a6c368dd36d21fd94689e9682bc3b012a5/NorthstarDedicatedTest/dedicated.cpp#L8).

First time working with C++ so be gentle.

2022-06-07 08:46 UTC, barnabwhy commented
You could compare `std::filesystem::last_write_time` with the last time that Northstar read from or wrote to the file to reduce the frequency that the file is parsed. It might also be worth adding in unban writing.

2022-06-07 08:53 UTC, barnabwhy commented
Also I think adding the IsDedicated check is bad given we can't then use bans on listen servers, maybe just find a way to tell if you're in the lobby?

2022-06-26 13:17 UTC, GeckoEidechse commented
I'm updating branch to sync it with upstream.

2022-07-04 21:49 UTC, GeckoEidechse requested changes
The issue with the current version as found in testing is that only reloads when banning/unbanning someone from console.

This excludes the case where someone would edit the `banlist.txt` file to ban someone. An example case would be where someone is hosting multiple servers that all use the same banlist, to avoid having to edit it for each server individually.
Therefore banlist should also be reloaded periodically based on some event or timer.

**EDIT:** A good place to reload banlist would be whenever a player connects (or disconnects).

2022-08-14 10:50 UTC, GeckoEidechse commented
Superseded by #233

2022-08-14 10:50 UTC, closed without merging

2022-08-14 10:51 UTC, GeckoEidechse commented on NorthstarDedicatedTest/serverauthentication.cpp
> +	if (IsDedicated() && !g_ServerBanSystem->IsUIDAllowed(nextPlayerUid))
Looking at this again I think this breaks banlist functionality completely for listen server ^^