Merge KittenPopo Additions
R2Northstar/NorthstarLauncher pull request #178
Opened 2022-05-26 03:53 UTC by KittenPopo

Seems pretty solid, tested it until I got bored.

Change summary:
- Added advanced debug info dump on crash to allow debugging of stack-corrupted crashes
- Improved KHook/NSMem stuff
- Default value for net_chan_limit_msec_per_sec to avoid dumb console spam
- Added debug-only logging
- Disable auth kicks when playing local games
- Added ANTI-RCE system

2022-05-26 22:01 UTC, KittenPopo commented
**NOTE**: NSQApi stuff is _NOT_ present in this pull request - don't worry about that.

2022-05-26 23:43 UTC, GeckoEidechse submitted a review, later dismissed

2022-05-26 23:43 UTC, GeckoEidechse commented on NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj
> -    <ClInclude Include="emit_blocker.h" />
Uh, probably don't wanna remove that :P

2022-05-27 00:14 UTC, GeckoEidechse commented on NorthstarDedicatedTest/NorthstarDedicatedTest.vcxproj
> -    <ClInclude Include="emit_blocker.h" />
Nevermind, got moved into `NorthstarDedicatedTest/ExploitFixes.cpp

2022-05-27 00:42 UTC, KittenPopo commented
Added exploit fixes, "consumed" emit_blocker hotfix into ExploitFixes.cpp hook.

![image](https://user-images.githubusercontent.com/28826980/170606207-caf15cac-7a6e-4617-9551-dff28dd5a8ae.png)

2022-05-30 22:19 UTC, GeckoEidechse commented
> I am also considering adding https://github.com/KittenPopo/NorthstarLauncher/tree/no-more-spdlog to this pr... :flushed:

That should be it's own PR if you want it changed. General rule of thumb: _1 PR == 1 feature change_

2022-05-31 17:02 UTC, KittenPopo commented
> > I am also considering adding https://github.com/KittenPopo/NorthstarLauncher/tree/no-more-spdlog to this pr... 😳
> 
> That should be it's own PR if you want it changed. General rule of thumb: _1 PR == 1 feature change_

Fair enough, that's gonna be a lot of PRs xD

2022-05-31 22:06 UTC, EladNLG requested changes

2022-05-31 22:09 UTC, KittenPopo commented on NorthstarDedicatedTest/clientchathooks.cpp
> -	g_ClientSquirrelManager->AddFuncRegistration("void", "NSChatWrite", "int context, string text", "", SQ_ChatWrite);
Fixed, thx. I was implementing a much cleaner and more format squirrel extension system that I removed in this PR, forgot to restore original functions (?).

2022-05-31 22:12 UTC, EladNLG commented on NorthstarDedicatedTest/clientchathooks.cpp
> -	g_ClientSquirrelManager->AddFuncRegistration("void", "NSChatWrite", "int context, string text", "", SQ_ChatWrite);
Restored, absolutely pog

2022-05-31 22:12 UTC, GeckoEidechse reviewed
Regarding all the changes from `spdlog::info` to `DBLOG`, what exactly is the reason for it? ^^"

2022-06-01 05:02 UTC, KittenPopo commented
> Regarding all the changes from `spdlog::info` to `DBLOG`, what exactly is the reason for it? ^^"

Such that spammy log messages don't fill the console except in debug mode.
In my no-more-spdlog pr it will log to a file but not print in console unless _DEBUG.

2022-06-01 08:49 UTC, GeckoEidechse commented
> Such that spammy log messages don't fill the console except in debug mode.

I mean, just use `spdlog::debug` and set log level appropriately (not sure if we do the second part yet).

2022-06-01 11:28 UTC, Mauler125 commented
> 

Why not guard the cout behind a ConVar? Also for spdlog you could set the level globally and exclude everything all together with 1 line. I was working on implementing a fast packet dumper with spdlog but the replacement with this new logger will break my PR.

2022-06-01 12:57 UTC, EladNLG approved these changes

2022-06-01 22:32 UTC, KittenPopo commented
> > 
> 
> Why not guard the cout behind a ConVar? Also for spdlog you could set the level globally and exclude everything all together with 1 line. I was working on implementing a fast packet dumper with spdlog (to dump the decrypted payload) but the replacement with this new logger will break my PR.

Yeah that's fair, tbh I'm just trying to get this PR done so that these fixes can get released. I told Bob this, but, feel free to revert the DLOGs back to spdlog::info.

2022-06-14 21:09 UTC, KittenPopo commented
Splitting this up into multiple because my pull request was too based

2022-06-14 21:09 UTC, closed without merging