Merge latest ExploitFixes.cpp updates
R2Northstar/NorthstarLauncher pull request #193
Opened 2022-06-14 21:32 UTC by KittenPopo

Commits from my fork added to this PR:
- https://github.com/R2Northstar/NorthstarLauncher/commit/11f04d371b4c572a30e6497c171f62a699f3be84
- https://github.com/R2Northstar/NorthstarLauncher/commit/a2b208a960e2b90ed534b380bda93486340ee7ef (not DLOG stuff)
- https://github.com/R2Northstar/NorthstarLauncher/commit/aff5ea1f4403155a20bdfae22c56b08cd4a11e79
- https://github.com/R2Northstar/NorthstarLauncher/commit/5b33e0b4181c4d46257228bad3b77f1326fd2e95

FEAR NOT: All new changes since my original PR to ExploitFixes (i.e. Script_GetEntByIndex hook) were added.

Should work just fine for everyone. Let me know if any changes are needed.

2022-06-14 21:44 UTC, GeckoEidechse requested changes

2022-06-14 21:44 UTC, GeckoEidechse commented on NorthstarDedicatedTest/ExploitFixes.cpp
> -	ENABLER_CREATEHOOK(hook, (char*)baseAddress + 0x2a8a50, &GetEntByIndexHook, reinterpret_cast<LPVOID*>(&GetEntByIndex));
This strips fixes by #191

2022-06-15 10:35 UTC, cpdt commented on NorthstarDedicatedTest/ExploitFixes.cpp
> -	ENABLER_CREATEHOOK(hook, (char*)baseAddress + 0x2a8a50, &GetEntByIndexHook, reinterpret_cast<LPVOID*>(&GetEntByIndex));
It was just moved to further up, using KHOOK:

https://github.com/R2Northstar/NorthstarLauncher/blob/561f97c223c2a71355592116bfa638690aebf6d2/NorthstarDedicatedTest/ExploitFixes.cpp#L74-L81

2022-06-15 10:38 UTC, cpdt commented on NorthstarDedicatedTest/ExploitFixes.cpp
> +#define ENTITYLIST_SLOT_COUNT 4096
All of the (not broken) native code seems to use 16384 (`0x4000`) when checking bounds for the entity array. Where does 4096 come from?

2022-06-15 12:18 UTC, GeckoEidechse commented on NorthstarDedicatedTest/ExploitFixes.cpp
> -	ENABLER_CREATEHOOK(hook, (char*)baseAddress + 0x2a8a50, &GetEntByIndexHook, reinterpret_cast<LPVOID*>(&GetEntByIndex));
Oh that's where it went. Thanks for linking <3

2022-06-15 22:34 UTC, KittenPopo commented on NorthstarDedicatedTest/ExploitFixes.cpp
> +#define ENTITYLIST_SLOT_COUNT 4096
https://developer.valvesoftware.com/wiki/Entity_index

2022-06-15 22:49 UTC, GeckoEidechse commented on NorthstarDedicatedTest/ExploitFixes.cpp
> +	name = {0, 0, 0}
Shouldn't `#defines` generally be at the top of the file for readability? ^^

2022-06-15 23:03 UTC, KittenPopo commented on NorthstarDedicatedTest/ExploitFixes.cpp
> +	name = {0, 0, 0}
It's for a specific function and is not used elsewhere. This is also a .cpp file, not a header, so it cannot (should not) be imported.
I can add #undef after the function or convert it to a template function if you'd like.

2022-06-17 01:33 UTC, closed without merging