New crashhandler
R2Northstar/NorthstarLauncher pull request #325
Opened 2022-11-08 21:29 UTC by emma-miler

This PR refactors the crashhandler and adds several new features:
* Support for catching runtime C++ exceptions
* Extended register dump support (segments, RIP, vector registers)
* Adds proper formatting to the error dump

Example of the new error log:
![image](https://user-images.githubusercontent.com/27428383/200679410-d5c38ea1-0195-4941-8b7f-3511332e1edf.png)

2022-11-12 13:46 UTC, BobTheBob9 requested changes
looks great mostly aside from lack of reinterpret_cast, may need some testing though

2022-11-12 13:46 UTC, BobTheBob9 commented on NorthstarDLL/crashhandler.cpp
> +		// Yes, i could use reinterpret cast, but this is more fun :)
come on bro

2022-11-12 13:46 UTC, BobTheBob9 commented on NorthstarDLL/crashhandler.cpp
> +
shouldn't have a newline here

2022-11-12 13:46 UTC, BobTheBob9 commented on NorthstarDLL/crashhandler.cpp
> +	spdlog::error("Northstar version: {}", version);
it could be good to dump all mod and plugin names/versions here too potentially

2022-11-12 14:29 UTC, emma-miler commented on NorthstarDLL/crashhandler.cpp
> +	spdlog::error("Northstar version: {}", version);
Will do for mods. Will add plugins when the new plugin system comes in, since i don't really track loaded plugins right now

2022-11-14 00:05 UTC, BobTheBob9 approved these changes

2022-11-14 00:05 UTC, merged

2022-11-26 23:55 UTC, pg9182 commented
This has caused issues with Docker:

```
ns-aitdm_dev_local-1  | 0024:fixme:dbghelp_dwarf:dwarf2_read_range no entry found
ns-aitdm_dev_local-1  | 0024:fixme:dbghelp_dwarf:dwarf2_read_range no entry found
ns-aitdm_dev_local-1  | 0024:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpScanMemory
```