fix dedicated server crash due to null sq context
R2Northstar/NorthstarLauncher pull request #341
Opened 2022-11-23 15:16 UTC by wolf109909

hi github

2022-11-23 15:18 UTC, wolf109909 commented
i fucked up a bit

2022-11-23 15:20 UTC, wolf109909 commented
why did i close it

2022-11-23 15:25 UTC, wolf109909 commented
why format fails (cries

2022-11-23 15:49 UTC, wolf109909 commented
it took me fucking 
30mins trying to fix clang format
i love myself

2022-11-23 23:13 UTC, GeckoEidechse requested changes
Can't say much about the code due to lack of C++ knowledge but I can point out typos and formatting suggestions :>

2022-11-23 23:13 UTC, GeckoEidechse commented on NorthstarDLL/hoststate.cpp
> +#include "dedicated.h"
```suggestion
#include "dedicated.h"

```

2022-11-23 23:13 UTC, GeckoEidechse commented on NorthstarDLL/hoststate.cpp
> +	// Don't run buffers that belongs to context that is not initialized on dedicated server
```suggestion
	// Don't run buffers that belong to context that is not initialized on dedicated server
```

2022-11-24 19:13 UTC, emma-miler approved these changes
While this PR does work, i think the underlying problem is that these contexts apparently do not get created properly on dedicated server, which i would consider to be a bug.

2022-11-27 16:31 UTC, GeckoEidechse commented
@pg9182 wanna test this with Docker?

2022-11-27 19:51 UTC, emma-miler commented
Superceded by #348

2022-11-27 20:28 UTC, closed without merging