Add script concommands
R2Northstar/NorthstarLauncher pull request #373
Opened 2022-12-17 17:41 UTC by emma-miler

Example: 
```
"ConCommands": [
	{
	  "Name": "concommand_test",
	  "Function": "ConCommandTest",
	  "Context": "UI",
	  "Flags": 0,
	  "HelpString": "example script concommand"
	}
  ],
  ```

2022-12-17 17:57 UTC, Erlite requested changes
Few formatting nitpicks, and potentially one logic issue with the switch statement.

2022-12-17 17:57 UTC, Erlite commented on NorthstarDLL/modmanager.cpp
> +			if (!concommandObj.IsObject() || !concommandObj.HasMember("Name") || !concommandObj.HasMember("Function") ||
Would it be possible to have braces here? The fact the conditions span two lines make it very confusing.

2022-12-17 17:57 UTC, Erlite commented on NorthstarDLL/modmanager.cpp
> +					concommand->Flags = concommandObj["Flags"].GetInt();
I'd also consider braces here since the else has some. Maybe a bit too nitpicky but it looks weird to me ^^'

2022-12-17 17:57 UTC, Erlite commented on NorthstarDLL/modmanager.cpp
> +	case ScriptContext::CLIENT:
Missing `break;` here?

2022-12-17 17:57 UTC, Erlite commented on NorthstarDLL/modmanager.cpp
> +		for (ModConCommand* command : mod.ConCommands)
The mix of no braces on the for and braces on the if really don't go well, maybe add braces?

2022-12-17 17:57 UTC, Erlite commented on NorthstarDLL/modmanager.cpp
> +							sCurrentFlag += sFlags[i];
Ditto?

2022-12-20 22:09 UTC, BobTheBob9 requested changes
looks great, just needs adjustments

2022-12-20 22:09 UTC, BobTheBob9 commented on NorthstarDLL/mods/modmanager.cpp
> +	if (g_pSquirrel<context>->m_pSQVM && g_pSquirrel<context>->m_pSQVM)
some logging here would be nice if the vm doesn't exist

2022-12-20 22:09 UTC, BobTheBob9 commented on NorthstarDLL/mods/modmanager.cpp
> +				}
the string flags parsing code here is duplicated from convars, it'd be nice if it was all in one helper function instead

2022-12-20 22:09 UTC, BobTheBob9 commented on NorthstarDLL/mods/modmanager.cpp
> +	ModConCommand* found = nullptr;
generally more spacing between statements in this function would be nice, not many newlines

2022-12-22 14:01 UTC, BobTheBob9 approved these changes

2022-12-22 18:59 UTC, merged