plugins: Allow plugins to customize their log colors
R2Northstar/NorthstarLauncher pull request #823
Opened 2024-09-12 11:13 UTC by uniboi

If the color flag is 0 (expected but undocumented default behaviour of plugins for GetField) NS::Colors::PLUGIN is used as a default.

The Color is packed into a 64 bit integer like this
```cpp
const Color = packed struct(u64) {
    red: u8,
    green: u8,
    blue: u8,
    _: u40 = 0,
};
```
The colors only occupy the **lower 3 bytes** of the integer. The remaining bits are ignored. When determining to use the default color or the provided log color, the lower 12 bits are checked if any is not 0.

2024-09-12 15:10 UTC, catornot commented
Were the plugin field and plugin string enums supposed to be non exhaustive?

2024-09-12 15:20 UTC, uniboi commented
yes to allow adding more fields in the future they're supposed to be non exhaustive

2024-09-12 16:44 UTC, catornot commented
Alright a few plugins crashing is fine for now ig
Will review this pr later today probably

2024-09-15 13:15 UTC, F1F7Y approved these changes

2024-09-15 13:15 UTC, F1F7Y commented on primedev/plugins/plugins.h
> +	Color m_logColor = NS::Colors::PLUGIN;
initialize in the constructor, not here thanks <3

2024-09-15 13:15 UTC, F1F7Y commented on primedev/plugins/interfaces/IPluginId.h
> +	static const int64_t COLOR_R_MASK = 0xFF;
Any reason for this to be in the header when its only needed in the constructor which is in a source file?

2024-09-15 13:24 UTC, F1F7Y requested changes
The above review wasnt supposed to be an approval smh

2024-10-03 00:04 UTC, catornot approved these changes
Looks good me thinks

also pretty colors for plugins :)
![image](https://github.com/user-attachments/assets/a83252d8-32d5-4d02-a870-b92496671db6)

2024-10-04 22:48 UTC, GeckoEidechse commented
Yeah so for some reason it renders as (almost?) black when the colour value is not set which looking at the code shouldn't be the case as it should just be default colour if not set

![image](https://github.com/user-attachments/assets/2272ea26-98a5-4290-aa64-e73319ed5c34)

2024-10-06 15:30 UTC, uniboi commented
Current rrplug builds return uninitialized values for colors. If a plugin returns 0 as color, a default will be used

2024-10-14 08:38 UTC, GeckoEidechse commented on primedev/plugins/plugins.cpp
> +	if ((logColor & 0xFFFFFF) != 0)
```suggestion
	// Apply custom colour if plugin has specified one
	if ((logColor & 0xFFFFFF) != 0)
```

2024-10-14 10:48 UTC, GeckoEidechse commented
cc @F1F7Y whether you wanna re-review, given that you requested changes. Otherwise if there's no response I'd merge within a day or two to not stall the PR o7

2024-10-14 11:19 UTC, F1F7Y approved these changes
Code looks acceptable

2024-10-14 13:20 UTC, merged