Startup args for r2modman
R2Northstar/NorthstarLauncher pull request #99
Opened 2022-02-27 18:20 UTC by emma-miler

Autogenerate `ns_startup_args.txt` and add flag to bypass `ns_startup_args.txt`

2022-02-27 18:36 UTC, laundmo requested changes

2022-02-27 18:36 UTC, laundmo commented on LauncherInjector/main.cpp
> +		if (!fs::exists("ns_startup_args.txt"))
```suggestion
		if (!fs::exists("ns_startup_args_dedi.txt"))
```

2022-02-28 13:25 UTC, emma-miler commented on LauncherInjector/main.cpp
> +			std::string defaultArgs = "-multiple -novid -noborder -windowed";
Oops, i forgot i modified my file. I just copied the stuff i had in mine and didnt think twice. Im not at my PC right now, so if you could PR the vanilla file onto my branch ill merge it. Ping me on discord if you do ^^

2022-02-28 14:05 UTC, GeckoEidechse commented on LauncherInjector/main.cpp
> +			std::string defaultArgs = "-multiple -novid -noborder -windowed";
It's
- `-multiple` for [`ns_startup_args.txt`](https://github.com/R2Northstar/Northstar/blob/main/release/ns_startup_args.txt)
- `+setplaylist private_match` for [`ns_startup_args_dedi.txt`](https://github.com/R2Northstar/Northstar/blob/main/release/ns_startup_args_dedi.txt)

^^

2022-02-28 15:09 UTC, pg9182 commented on LauncherInjector/main.cpp
> +			std::string defaultArgs = "-multiple -novid -noborder -windowed";
About `+setplaylist private_match`, I actually think we should.consider making it set it if it's not provided by default if there aren't any downsides.

2022-02-28 19:58 UTC, abarichello requested changes
Format check is failing https://github.com/R2Northstar/NorthstarLauncher/runs/5363501103?check_suite_focus=true

2022-02-28 20:26 UTC, abarichello approved these changes
Thanks, can you also add the new startup argument to the wiki? (targeting next-release branch) https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/launch-arguments

2022-02-28 20:27 UTC, merged